### ISSUE TITLE
Commit gradle wrapper files and batch files to the repo

### ISSUE THREAD

**Issue by RAnders00** [ephys/Omnifluids#3]
They are neccessary parts of the project and tell which version of gradle you are using. It's also a huge pain to develop on your mod if there are no wrapper files and scripts available (you would have to generate wrapper files on your own)

This is also the common way of doing it, I have never seen a repo not commit gradle wrapper files and scripts before.

Simply remove the following files from `.gitignore`:
- `gradle/wrapper/gradle-wrapper.jar`
- `gradle/wrapper/gradle-wrapper.properties`
- `gradlew.bat`
- `gradlew`

**Comment by jakimfett** [comment]
> I have never seen a repo not commit gradle wrapper files and scripts before.  

I don't check in the gradle wrapper, build scripts, IDE specific project files, or binary files. Now you can say you've [seen it all](https://github.com/jakimfett/Minechem).

**Comment by RAnders00** [comment]
@jakimfett That's **extremely** annoying for others. But feel free to, you've seen my arguments above.
